### ISSUE TITLE
SetupSequence() is not thread-safe

### ISSUE THREAD

**Issue by icalvo** [moq/moq4#467]
`SetupSequence()` is not thread-safe. If two threads call the mock, it can return the same value more than once. The following failing test demonstrate it:

```csharp
using System.Collections.Concurrent;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;

namespace MoqTests
{
    [TestClass]
    public class SetupSequenceTests
    {
        private interface ITest
        {
            int Method();
        }

        [TestMethod]
        public async Task Test()
        {
            const int length = 20;

            var m = new Mock<ITest>();

            // Setups the mock to return a sequence of results.
            var seqSetup = m.SetupSequence(x => x.Method());
            for (int i = 1; i <= length; i++)
            {
                seqSetup = seqSetup
                    .Returns(i);
            }
            
            // Queue to store the invocations of the mock.
            var invocationsQueue = new ConcurrentQueue<int>();

            // We will invoke the mock from two different tasks.
            var t1 = Task.Run(() => RegisterInvocations(m, invocationsQueue));
            var t2 = Task.Run(() => RegisterInvocations(m, invocationsQueue));
            await Task.WhenAll(t1, t2);

            var orderedInvocations = invocationsQueue.OrderBy(x => x).ToArray();

            // The assertion prints the real invocations, you will see duplicates there!
            CollectionAssert.AreEqual(
                Enumerable.Range(1, length).ToArray(),
                orderedInvocations,
                string.Join(", ", orderedInvocations.Select(x => x.ToString())));
        }

        // Calls the mock until it returns default(int)
        private static void RegisterInvocations(IMock<ITest> m, ConcurrentQueue<int> invocationsQueue)
        {
            int result;
            do
            {
                result = m.Object.Method();
                if (result != default(int))
                {
                    invocationsQueue.Enqueue(result);
                }
            } while (result != default(int));
        }
    }
}
```

**Comment by stakx** [comment]
Hi @icalvo, and thanks for reporting this. Would you like to attempt a fix? If so, please feel free to send a PR (against the `develop` branch).

**Comment by stakx** [comment]
`SetupSequence` is currently built on top of several other parts of the public API (`When`, `Callback`, `Throws` and `Returns`). The thread-safety issue reported here exists because comparing the invocation count ("current step number") happens in `When`, but it's increased via `Callback`... that is, the increment doesn't happen atomically.

In order to make `SetupSequence` thread-safe, it seems likely that this approach must be given up. Instead, a new `MethodCall` subclass needs to be implemented that overrides `Execute` to do everything at once. Then we'll have a change to do atomic increments etc.

**Comment by stakx** [comment]
@icalvo - There's a tradeoff here: Given Moq's current architecture, it is very difficult to make `SetupSequence` thread-safe without introducing functional changes. The major change would be that `SetupSequence` would now override pre-existing setups for identical invocations, where previously it didn't override them.

The previous (current) behaviour of Moq can be useful because it allows you to first setup a default action or return value for an invocation, then partially override that default with a second sequence setup. Once the sequence is exhausted, invocations will do whatever the initial setup says.

I'm fine with this breaking, functional change because it brings `SetupSequence` more in line with how the other `Setup` methods work. But what's probably missing with the new behaviour is additional methods on sequences such as `.ReturnsWhenExhausted` and `.ThrowsWhenExhausted` (or pick any other name) that defines what the default action or return value is for an exhausted sequence.

What are your thoughts on this?

**Comment by rusanov-vladimir** [comment]
While this issue isn't solved I've used approach Haacked [blogged about](https://haacked.com/archive/2010/11/24/moq-sequences-revisited.aspx/). 
This extension method seems to be working fine in parallel scenarios:

```
 public static void ReturnsInOrder<T, TResult>(this ISetup<T, TResult> setup,
     params object[] results) where T : class {
   var queue = new Queue(results);
     setup.Returns(() => {
         var result = queue.Dequeue();
         if (result is Exception) {
             throw result as Exception;
         }
         return (TResult)result;
     });
 }
```

**Comment by stakx** [comment]
@icalvo, @rusanov-vladimir - I just published a pre-release version `4.8.0-rc1` on NuGet. It contains (among other things) a re-implementation of `SetupSequence` that should now be thread-safe.

**Comment by zxxc** [comment]
Hi, we are using 4.8.1 and issue it still persists
 _client.SetupSequence(c => c.Get(It.IsAny<string>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(resp1)
                .ThrowsAsync(exceptionForBrokenRequest);
Is this issue fixed for Throws and ThrowsAsync?

**Comment by stakx** [comment]
Can you provide a minimal code example that reproduces the issue you're referring to? Otherwise it's a little hard to tell what precisely we're talking about.

**Comment by zxxc** [comment]
Sorry it's my fault. I was using it wrong
I need for particular values throw exception
And for other return value
And i'm starting it in parallel

seems  _client.SetupSequence() is not suitable for this
and i need to combine somehow two lines
_client.Setup(c=>c.Get(1)).Returns(id=> return dic[id]);

_client.Setup(c=>c.Get(2)).Throws();
