### ISSUE TITLE
SetupAllProperties() and Mock.Of<T> regression in Moq 4.12.0

### ISSUE THREAD

**Issue by mattzink** [moq/moq4#870]
The following tests pass with Moq 4.11.0 and fail with 4.12.0:

```csharp
var httpContext = Mock.Of<Microsoft.AspNetCore.Http.HttpContext>();
httpContext.Items = new Dictionary<object, object>();
Assert.NotNull(httpContext.Items);
```
```csharp
var httpContext = new Mock<Microsoft.AspNetCore.Http.HttpContext>()
    .SetupAllProperties();
httpContext.Object.Items = new Dictionary<object, object>();
Assert.NotNull(httpContext.Object.Items);
```

This seems to be very likely caused by https://github.com/moq/moq4/pull/826
Perhaps this new code doesn't handle abstract types correctly?

Environment: Windows x64, .NET Core 2.2.1

**Comment by mattzink** [comment]
This pattern also fails:
```csharp
var httpContext = Mock.Of<HttpContext>(
    context => context.Items == new Dictionary<object, object>());
Assert.NotNull(httpContext.Items);
```

**Comment by stakx** [comment]
Thanks for reporting, @mattzink. I've found the regression. The problem lies here:

https://github.com/moq/moq4/blob/731567c12159d855658726479eda8d25626ae8b9/src/Moq/Extensions.cs#L51-L59

`.StartsWith` should be `.Equals`. I'm about to push a bug fix to `master`.

**Comment by mattzink** [comment]
Ahh, so it's because the property name is "Items" that it thinks it's an indexer. Interesting!

**Comment by stakx** [comment]
Yes, `SetupAllProperties` does not set up indexers (and never has, AFAIK). Under the hood, indexers look like parameterized properties called `Item`. (Though the name can be customized, which Moq currently doesn't account for.)

Fixed in master. Watch out for an updated version of Moq later this month!

**Comment by kaan-kaya** [comment]
So even with this fix, this issue remains for properties called Item, then?

**Comment by stakx** [comment]
@kaan-kaya, good point. I suppose it's time to finally fix the indexer recognition logic.
